/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentsRouteImport } from './routes/tents'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FootwearRouteImport } from './routes/footwear'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CarriersRouteImport } from './routes/carriers'
import { Route as ApparelRouteImport } from './routes/apparel'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as EnSplatRouteImport } from './routes/en/$'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLanguagesRouteImport } from './routes/admin/languages'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminGlossaryRouteImport } from './routes/admin/glossary'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAttributesRouteImport } from './routes/admin/attributes'
import { Route as LangPermintaanRouteImport } from './routes/$lang.permintaan'
import { Route as LangInquiryRouteImport } from './routes/$lang.inquiry'
import { Route as LangPermintaanIndexRouteImport } from './routes/$lang.permintaan.index'
import { Route as LangInquiryIndexRouteImport } from './routes/$lang.inquiry.index'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products.new'
import { Route as LangProdukSlugRouteImport } from './routes/$lang.produk.$slug'
import { Route as LangProductsSlugRouteImport } from './routes/$lang.products.$slug'
import { Route as LangPermintaanTerkirimRouteImport } from './routes/$lang.permintaan.terkirim'
import { Route as LangInquirySentRouteImport } from './routes/$lang.inquiry.sent'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin/products.$id.edit'

const TentsRoute = TentsRouteImport.update({
  id: '/tents',
  path: '/tents',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FootwearRoute = FootwearRouteImport.update({
  id: '/footwear',
  path: '/footwear',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CarriersRoute = CarriersRouteImport.update({
  id: '/carriers',
  path: '/carriers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApparelRoute = ApparelRouteImport.update({
  id: '/apparel',
  path: '/apparel',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const EnSplatRoute = EnSplatRouteImport.update({
  id: '/en/$',
  path: '/en/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLanguagesRoute = AdminLanguagesRouteImport.update({
  id: '/admin/languages',
  path: '/admin/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/admin/inquiries',
  path: '/admin/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGlossaryRoute = AdminGlossaryRouteImport.update({
  id: '/admin/glossary',
  path: '/admin/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttributesRoute = AdminAttributesRouteImport.update({
  id: '/admin/attributes',
  path: '/admin/attributes',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPermintaanRoute = LangPermintaanRouteImport.update({
  id: '/permintaan',
  path: '/permintaan',
  getParentRoute: () => LangRoute,
} as any)
const LangInquiryRoute = LangInquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => LangRoute,
} as any)
const LangPermintaanIndexRoute = LangPermintaanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangPermintaanRoute,
} as any)
const LangInquiryIndexRoute = LangInquiryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangInquiryRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const LangProdukSlugRoute = LangProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangProductsSlugRoute = LangProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangPermintaanTerkirimRoute = LangPermintaanTerkirimRouteImport.update({
  id: '/terkirim',
  path: '/terkirim',
  getParentRoute: () => LangPermintaanRoute,
} as any)
const LangInquirySentRoute = LangInquirySentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => LangInquiryRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/accessories': typeof AccessoriesRoute
  '/apparel': typeof ApparelRoute
  '/carriers': typeof CarriersRoute
  '/catalog': typeof CatalogRoute
  '/footwear': typeof FootwearRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/tents': typeof TentsRoute
  '/$lang/inquiry': typeof LangInquiryRouteWithChildren
  '/$lang/permintaan': typeof LangPermintaanRouteWithChildren
  '/admin/attributes': typeof AdminAttributesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/glossary': typeof AdminGlossaryRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/c/$slug': typeof CSlugRoute
  '/en/$': typeof EnSplatRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/en/': typeof EnIndexRoute
  '/$lang/inquiry/sent': typeof LangInquirySentRoute
  '/$lang/permintaan/terkirim': typeof LangPermintaanTerkirimRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/produk/$slug': typeof LangProdukSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/$lang/inquiry/': typeof LangInquiryIndexRoute
  '/$lang/permintaan/': typeof LangPermintaanIndexRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/apparel': typeof ApparelRoute
  '/carriers': typeof CarriersRoute
  '/catalog': typeof CatalogRoute
  '/footwear': typeof FootwearRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/tents': typeof TentsRoute
  '/admin/attributes': typeof AdminAttributesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/glossary': typeof AdminGlossaryRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/c/$slug': typeof CSlugRoute
  '/en/$': typeof EnSplatRoute
  '/$lang': typeof LangIndexRoute
  '/admin': typeof AdminIndexRoute
  '/en': typeof EnIndexRoute
  '/$lang/inquiry/sent': typeof LangInquirySentRoute
  '/$lang/permintaan/terkirim': typeof LangPermintaanTerkirimRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/produk/$slug': typeof LangProdukSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/$lang/inquiry': typeof LangInquiryIndexRoute
  '/$lang/permintaan': typeof LangPermintaanIndexRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/accessories': typeof AccessoriesRoute
  '/apparel': typeof ApparelRoute
  '/carriers': typeof CarriersRoute
  '/catalog': typeof CatalogRoute
  '/footwear': typeof FootwearRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRoute
  '/tents': typeof TentsRoute
  '/$lang/inquiry': typeof LangInquiryRouteWithChildren
  '/$lang/permintaan': typeof LangPermintaanRouteWithChildren
  '/admin/attributes': typeof AdminAttributesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/glossary': typeof AdminGlossaryRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/c/$slug': typeof CSlugRoute
  '/en/$': typeof EnSplatRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/en/': typeof EnIndexRoute
  '/$lang/inquiry/sent': typeof LangInquirySentRoute
  '/$lang/permintaan/terkirim': typeof LangPermintaanTerkirimRoute
  '/$lang/products/$slug': typeof LangProductsSlugRoute
  '/$lang/produk/$slug': typeof LangProdukSlugRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/$lang/inquiry/': typeof LangInquiryIndexRoute
  '/$lang/permintaan/': typeof LangPermintaanIndexRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/accessories'
    | '/apparel'
    | '/carriers'
    | '/catalog'
    | '/footwear'
    | '/sitemap.xml'
    | '/stores'
    | '/tents'
    | '/$lang/inquiry'
    | '/$lang/permintaan'
    | '/admin/attributes'
    | '/admin/categories'
    | '/admin/forgot-password'
    | '/admin/glossary'
    | '/admin/inquiries'
    | '/admin/languages'
    | '/admin/login'
    | '/admin/products'
    | '/admin/reset-password'
    | '/c/$slug'
    | '/en/$'
    | '/$lang/'
    | '/admin/'
    | '/en/'
    | '/$lang/inquiry/sent'
    | '/$lang/permintaan/terkirim'
    | '/$lang/products/$slug'
    | '/$lang/produk/$slug'
    | '/admin/products/new'
    | '/$lang/inquiry/'
    | '/$lang/permintaan/'
    | '/admin/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessories'
    | '/apparel'
    | '/carriers'
    | '/catalog'
    | '/footwear'
    | '/sitemap.xml'
    | '/stores'
    | '/tents'
    | '/admin/attributes'
    | '/admin/categories'
    | '/admin/forgot-password'
    | '/admin/glossary'
    | '/admin/inquiries'
    | '/admin/languages'
    | '/admin/login'
    | '/admin/products'
    | '/admin/reset-password'
    | '/c/$slug'
    | '/en/$'
    | '/$lang'
    | '/admin'
    | '/en'
    | '/$lang/inquiry/sent'
    | '/$lang/permintaan/terkirim'
    | '/$lang/products/$slug'
    | '/$lang/produk/$slug'
    | '/admin/products/new'
    | '/$lang/inquiry'
    | '/$lang/permintaan'
    | '/admin/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/accessories'
    | '/apparel'
    | '/carriers'
    | '/catalog'
    | '/footwear'
    | '/sitemap.xml'
    | '/stores'
    | '/tents'
    | '/$lang/inquiry'
    | '/$lang/permintaan'
    | '/admin/attributes'
    | '/admin/categories'
    | '/admin/forgot-password'
    | '/admin/glossary'
    | '/admin/inquiries'
    | '/admin/languages'
    | '/admin/login'
    | '/admin/products'
    | '/admin/reset-password'
    | '/c/$slug'
    | '/en/$'
    | '/$lang/'
    | '/admin/'
    | '/en/'
    | '/$lang/inquiry/sent'
    | '/$lang/permintaan/terkirim'
    | '/$lang/products/$slug'
    | '/$lang/produk/$slug'
    | '/admin/products/new'
    | '/$lang/inquiry/'
    | '/$lang/permintaan/'
    | '/admin/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AccessoriesRoute: typeof AccessoriesRoute
  ApparelRoute: typeof ApparelRoute
  CarriersRoute: typeof CarriersRoute
  CatalogRoute: typeof CatalogRoute
  FootwearRoute: typeof FootwearRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoresRoute: typeof StoresRoute
  TentsRoute: typeof TentsRoute
  AdminAttributesRoute: typeof AdminAttributesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminGlossaryRoute: typeof AdminGlossaryRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminLanguagesRoute: typeof AdminLanguagesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  CSlugRoute: typeof CSlugRoute
  EnSplatRoute: typeof EnSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
  EnIndexRoute: typeof EnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tents': {
      id: '/tents'
      path: '/tents'
      fullPath: '/tents'
      preLoaderRoute: typeof TentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footwear': {
      id: '/footwear'
      path: '/footwear'
      fullPath: '/footwear'
      preLoaderRoute: typeof FootwearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carriers': {
      id: '/carriers'
      path: '/carriers'
      fullPath: '/carriers'
      preLoaderRoute: typeof CarriersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apparel': {
      id: '/apparel'
      path: '/apparel'
      fullPath: '/apparel'
      preLoaderRoute: typeof ApparelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/en/$': {
      id: '/en/$'
      path: '/en/$'
      fullPath: '/en/$'
      preLoaderRoute: typeof EnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/languages': {
      id: '/admin/languages'
      path: '/admin/languages'
      fullPath: '/admin/languages'
      preLoaderRoute: typeof AdminLanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/admin/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/glossary': {
      id: '/admin/glossary'
      path: '/admin/glossary'
      fullPath: '/admin/glossary'
      preLoaderRoute: typeof AdminGlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attributes': {
      id: '/admin/attributes'
      path: '/admin/attributes'
      fullPath: '/admin/attributes'
      preLoaderRoute: typeof AdminAttributesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/permintaan': {
      id: '/$lang/permintaan'
      path: '/permintaan'
      fullPath: '/$lang/permintaan'
      preLoaderRoute: typeof LangPermintaanRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/inquiry': {
      id: '/$lang/inquiry'
      path: '/inquiry'
      fullPath: '/$lang/inquiry'
      preLoaderRoute: typeof LangInquiryRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/permintaan/': {
      id: '/$lang/permintaan/'
      path: '/'
      fullPath: '/$lang/permintaan/'
      preLoaderRoute: typeof LangPermintaanIndexRouteImport
      parentRoute: typeof LangPermintaanRoute
    }
    '/$lang/inquiry/': {
      id: '/$lang/inquiry/'
      path: '/'
      fullPath: '/$lang/inquiry/'
      preLoaderRoute: typeof LangInquiryIndexRouteImport
      parentRoute: typeof LangInquiryRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/$lang/produk/$slug': {
      id: '/$lang/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/$lang/produk/$slug'
      preLoaderRoute: typeof LangProdukSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/products/$slug': {
      id: '/$lang/products/$slug'
      path: '/products/$slug'
      fullPath: '/$lang/products/$slug'
      preLoaderRoute: typeof LangProductsSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/permintaan/terkirim': {
      id: '/$lang/permintaan/terkirim'
      path: '/terkirim'
      fullPath: '/$lang/permintaan/terkirim'
      preLoaderRoute: typeof LangPermintaanTerkirimRouteImport
      parentRoute: typeof LangPermintaanRoute
    }
    '/$lang/inquiry/sent': {
      id: '/$lang/inquiry/sent'
      path: '/sent'
      fullPath: '/$lang/inquiry/sent'
      preLoaderRoute: typeof LangInquirySentRouteImport
      parentRoute: typeof LangInquiryRoute
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminProductsRoute
    }
  }
}

interface LangInquiryRouteChildren {
  LangInquirySentRoute: typeof LangInquirySentRoute
  LangInquiryIndexRoute: typeof LangInquiryIndexRoute
}

const LangInquiryRouteChildren: LangInquiryRouteChildren = {
  LangInquirySentRoute: LangInquirySentRoute,
  LangInquiryIndexRoute: LangInquiryIndexRoute,
}

const LangInquiryRouteWithChildren = LangInquiryRoute._addFileChildren(
  LangInquiryRouteChildren,
)

interface LangPermintaanRouteChildren {
  LangPermintaanTerkirimRoute: typeof LangPermintaanTerkirimRoute
  LangPermintaanIndexRoute: typeof LangPermintaanIndexRoute
}

const LangPermintaanRouteChildren: LangPermintaanRouteChildren = {
  LangPermintaanTerkirimRoute: LangPermintaanTerkirimRoute,
  LangPermintaanIndexRoute: LangPermintaanIndexRoute,
}

const LangPermintaanRouteWithChildren = LangPermintaanRoute._addFileChildren(
  LangPermintaanRouteChildren,
)

interface LangRouteChildren {
  LangInquiryRoute: typeof LangInquiryRouteWithChildren
  LangPermintaanRoute: typeof LangPermintaanRouteWithChildren
  LangIndexRoute: typeof LangIndexRoute
  LangProductsSlugRoute: typeof LangProductsSlugRoute
  LangProdukSlugRoute: typeof LangProdukSlugRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangInquiryRoute: LangInquiryRouteWithChildren,
  LangPermintaanRoute: LangPermintaanRouteWithChildren,
  LangIndexRoute: LangIndexRoute,
  LangProductsSlugRoute: LangProductsSlugRoute,
  LangProdukSlugRoute: LangProdukSlugRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface AdminProductsRouteChildren {
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AccessoriesRoute: AccessoriesRoute,
  ApparelRoute: ApparelRoute,
  CarriersRoute: CarriersRoute,
  CatalogRoute: CatalogRoute,
  FootwearRoute: FootwearRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoresRoute: StoresRoute,
  TentsRoute: TentsRoute,
  AdminAttributesRoute: AdminAttributesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminGlossaryRoute: AdminGlossaryRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminLanguagesRoute: AdminLanguagesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  CSlugRoute: CSlugRoute,
  EnSplatRoute: EnSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
  EnIndexRoute: EnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
